/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_elite_tools_imgtools_hook_SysHook */

#ifndef _Included_com_elite_tools_imgtools_hook_SysHook
#define _Included_com_elite_tools_imgtools_hook_SysHook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_elite_tools_imgtools_hook_SysHook
 * Method:    registerHook
 * Signature: (Lcom/elite/tools/imgtools/hook/GlobalEventListener;)V
 */
JNIEXPORT void JNICALL Java_com_elite_tools_imgtools_hook_SysHook_registerHook
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_elite_tools_imgtools_hook_SysHook
 * Method:    unRegisterHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_elite_tools_imgtools_hook_SysHook_unRegisterHook
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
